name: nanobiopsy
channels:
  - bioconda
  - pytorch
  - conda-forge
  - nvidia
  - defaults
name: nanobiopsy
channels:
  - bioconda
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - alembic=1.14.0
  - aom=3.9.1
  - asttokens=2.4.1
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-blosc2=2.15.1
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - charls=2.4.2
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.55.0
  - freetype=2.12.1
  - giflib=5.2.2
  - greenlet=3.1.1
  - icu=75.1
  - imagecodecs=2024.9.22
  - imageio=2.36.0
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.3
  - libavif16=1.1.1
  - libblas=3.9.0
  - libboost=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libhwy=1.1.0
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.0
  - liblapack=3.9.0
  - liblightgbm=4.5.0
  - libllvm14=14.0.6
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=2.1.2
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lightgbm=4.5.0
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - mako=1.3.6
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numba=0.60.0
  - numpy=2.0.2
  - ocl-icd=2.3.2
  - openjpeg=2.5.2
  - openssl=3.4.0
  - optuna=4.1.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - plotly=5.24.1
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.2
  - pygments=2.18.0
  - pymzml=2.5.10
  - pyparsing=3.2.0
  - python=3.11.10
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytz=2024.1
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - rav1e=0.6.6
  - readline=8.2
  - regex=2024.11.6
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.6.0
  - shap=0.46.0
  - six=1.16.0
  - slicer=0.0.8
  - snappy=1.2.1
  - sqlalchemy=2.0.36
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - svt-av1=2.3.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tifffile=2024.9.20
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.67.0
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.21.0
  - zlib-ng=2.2.2
  - zstd=1.5.6
  - pip:
      - pyimzml==1.5.5
      - wheezy-template==3.2.3

      - pyimzml==1.5.5
      - wheezy-template==3.2.3
